document.addEventListener("DOMContentLoaded", function () {
  const latin1Letters = [
    ["À", "Capital A Grave", "latin1-00c0"],
    ["Á", "Capital A Acute", "latin1-00c1"],
    ["Â", "Capital A Circumflex", "latin1-00c2"],
    ["Ã", "Capital A Tilde", "latin1-00c3"],
    ["Ä", "Capital A Diaeresis", "latin1-00c4"],
    ["Å", "Capital A Ring Above", "latin1-00c5"],
    ["Æ", "Capital Ae", "latin1-00c6"],
    ["Ç", "Capital C Cedilla", "latin1-00c7"],
    ["È", "Capital E Grave", "latin1-00c8"],
    ["É", "Capital E Acute", "latin1-00c9"],
    ["Ê", "Capital E Circumflex", "latin1-00ca"],
    ["Ë", "Capital E Diaeresis", "latin1-00cb"],
    ["Ì", "Capital I Grave", "latin1-00cc"],
    ["Í", "Capital I Acute", "latin1-00cd"],
    ["Î", "Capital I Circumflex", "latin1-00ce"],
    ["Ï", "Capital I Diaeresis", "latin1-00cf"],
    ["Ð", "Capital Eth", "latin1-00d0"],
    ["Ñ", "Capital N Tilde", "latin1-00d1"],
    ["Ò", "Capital O Grave", "latin1-00d2"],
    ["Ó", "Capital O Acute", "latin1-00d3"],
    ["Ô", "Capital O Circumflex", "latin1-00d4"],
    ["Õ", "Capital O Tilde", "latin1-00d5"],
    ["Ö", "Capital O Diaeresis", "latin1-00d6"],
    ["Ø", "Capital O Stroke", "latin1-00d8"],
    ["Ù", "Capital U Grave", "latin1-00d9"],
    ["Ú", "Capital U Acute", "latin1-00da"],
    ["Û", "Capital U Circumflex", "latin1-00db"],
    ["Ü", "Capital U Diaeresis", "latin1-00dc"],
    ["Ý", "Capital Y Acute", "latin1-00dd"],
    ["Þ", "Capital Thorn", "latin1-00de"],
    ["ß", "Small Sharp S", "latin1-00df"],
    ["à", "Small A Grave", "latin1-00e0"],
    ["á", "Small A Acute", "latin1-00e1"],
    ["â", "Small A Circumflex", "latin1-00e2"],
    ["ã", "Small A Tilde", "latin1-00e3"],
    ["ä", "Small A Diaeresis", "latin1-00e4"],
    ["å", "Small A Ring Above", "latin1-00e5"],
    ["æ", "Small Ae", "latin1-00e6"],
    ["ç", "Small C Cedilla", "latin1-00e7"],
    ["è", "Small E Grave", "latin1-00e8"],
    ["é", "Small E Acute", "latin1-00e9"],
    ["ê", "Small E Circumflex", "latin1-00ea"],
    ["ë", "Small E Diaeresis", "latin1-00eb"],
    ["ì", "Small I Grave", "latin1-00ec"],
    ["í", "Small I Acute", "latin1-00ed"],
    ["î", "Small I Circumflex", "latin1-00ee"],
    ["ï", "Small I Diaeresis", "latin1-00ef"],
    ["ð", "Small Eth", "latin1-00f0"],
    ["ñ", "Small N Tilde", "latin1-00f1"],
    ["ò", "Small O Grave", "latin1-00f2"],
    ["ó", "Small O Acute", "latin1-00f3"],
    ["ô", "Small O Circumflex", "latin1-00f4"],
    ["õ", "Small O Tilde", "latin1-00f5"],
    ["ö", "Small O Diaeresis", "latin1-00f6"],
    ["ø", "Small O Stroke", "latin1-00f8"],
    ["ù", "Small U Grave", "latin1-00f9"],
    ["ú", "Small U Acute", "latin1-00fa"],
    ["û", "Small U Circumflex", "latin1-00fb"],
    ["ü", "Small U Diaeresis", "latin1-00fc"],
    ["ý", "Small Y Acute", "latin1-00fd"],
    ["þ", "Small Thorn", "latin1-00fe"],
    ["ÿ", "Small Y Diaeresis", "latin1-00ff"],
  ];

  const latinExtA1Letters = [
    ["Ā", "Capital A Macron", "exta1-0100"],
    ["ā", "Small A Macron", "exta1-0101"],
    ["Ă", "Capital A Breve", "exta1-0102"],
    ["ă", "Small A Breve", "exta1-0103"],
    ["Ą", "Capital A Ogonek", "exta1-0104"],
    ["ą", "Small A Ogonek", "exta1-0105"],
    ["Ć", "Capital C Acute", "exta1-0106"],
    ["ć", "Small C Acute", "exta1-0107"],
    ["Ĉ", "Capital C Circumflex", "exta1-0108"],
    ["ĉ", "Small C Circumflex", "exta1-0109"],
    ["Ċ", "Capital C Dot Above", "exta1-010a"],
    ["ċ", "Small C Dot Above", "exta1-010b"],
    ["Č", "Capital C Caron", "exta1-010c"],
    ["č", "Small C Caron", "exta1-010d"],
    ["Ď", "Capital D Caron", "exta1-010e"],
    ["ď", "Small D Caron", "exta1-010f"],
    ["Đ", "Capital D Stroke", "exta1-0110"],
    ["đ", "Small D Stroke", "exta1-0111"],
    ["Ē", "Capital E Macron", "exta1-0112"],
    ["ē", "Small E Macron", "exta1-0113"],
    ["Ĕ", "Capital E Breve", "exta1-0114"],
    ["ĕ", "Small E Breve", "exta1-0115"],
    ["Ė", "Capital E Dot Above", "exta1-0116"],
    ["ė", "Small E Dot Above", "exta1-0117"],
    ["Ę", "Capital E Ogonek", "exta1-0118"],
    ["ę", "Small E Ogonek", "exta1-0119"],
    ["Ě", "Capital E Caron", "exta1-011a"],
    ["ě", "Small E Caron", "exta1-011b"],
    ["Ĝ", "Capital G Circumflex", "exta1-011c"],
    ["ĝ", "Small G Circumflex", "exta1-011d"],
    ["Ğ", "Capital G Breve", "exta1-011e"],
    ["ğ", "Small G Breve", "exta1-011f"],
    ["Ġ", "Capital G Dot Above", "exta1-0120"],
    ["ġ", "Small G Dot Above", "exta1-0121"],
    ["Ģ", "Capital G Cedilla", "exta1-0122"],
    ["ģ", "Small G Cedilla", "exta1-0123"],
    ["Ĥ", "Capital H Circumflex", "exta1-0124"],
    ["ĥ", "Small H Circumflex", "exta1-0125"],
    ["Ħ", "Capital H Stroke", "exta1-0126"],
    ["ħ", "Small H Stroke", "exta1-0127"],
    ["Ĩ", "Capital I Tilde", "exta1-0128"],
    ["ĩ", "Small I Tilde", "exta1-0129"],
    ["Ī", "Capital I Macron", "exta1-012a"],
    ["ī", "Small I Macron", "exta1-012b"],
    ["Ĭ", "Capital I Breve", "exta1-012c"],
    ["ĭ", "Small I Breve", "exta1-012d"],
    ["Į", "Capital I Ogonek", "exta1-012e"],
    ["į", "Small I Ogonek", "exta1-012f"],
    ["İ", "Capital I Dot Above", "exta1-0130"],
    ["ı", "Small Dotless I", "exta1-0131"],
    ["Ĳ", "Capital Ij", "exta1-0132"],
    ["ĳ", "Small Ij", "exta1-0133"],
    ["Ĵ", "Capital J Circumflex", "exta1-0134"],
    ["ĵ", "Small J Circumflex", "exta1-0135"],
    ["Ķ", "Capital K Cedilla", "exta1-0136"],
    ["ķ", "Small K Cedilla", "exta1-0137"],
    ["ĸ", "Small Kra", "exta1-0138"],
    ["Ĺ", "Capital L Acute", "exta1-0139"],
    ["ĺ", "Small L Acute", "exta1-013a"],
    ["Ļ", "Capital L Cedilla", "exta1-013b"],
    ["ļ", "Small L Cedilla", "exta1-013c"],
    ["Ľ", "Capital L Caron", "exta1-013d"],
    ["ľ", "Small L Caron", "exta1-013e"],
    ["Ŀ", "Capital L Middle Dot", "exta1-013f"],
  ];

  const latinExtA2Letters = [
    ["ŀ", "Small L Middle Dot", "exta2-0140"],
    ["Ł", "Capital L Stroke", "exta2-0141"],
    ["ł", "Small L Stroke", "exta2-0142"],
    ["Ń", "Capital N Acute", "exta2-0143"],
    ["ń", "Small N Acute", "exta2-0144"],
    ["Ņ", "Capital N Cedilla", "exta2-0145"],
    ["ņ", "Small N Cedilla", "exta2-0146"],
    ["Ň", "Capital N Caron", "exta2-0147"],
    ["ň", "Small N Caron", "exta2-0148"],
    ["ŉ", "Small N Preceded By Apostrophe", "exta2-0149"],
    ["Ŋ", "Capital Eng", "exta2-014a"],
    ["ŋ", "Small Eng", "exta2-014b"],
    ["Ō", "Capital O Macron", "exta2-014c"],
    ["ō", "Small O Macron", "exta2-014d"],
    ["Ŏ", "Capital O Breve", "exta2-014e"],
    ["ŏ", "Small O Breve", "exta2-014f"],
    ["Ő", "Capital O Double Acute", "exta2-0150"],
    ["ő", "Small O Double Acute", "exta2-0151"],
    ["Œ", "Capital Oe", "exta2-0152"],
    ["œ", "Small Oe", "exta2-0153"],
    ["Ŕ", "Capital R Acute", "exta2-0154"],
    ["ŕ", "Small R Acute", "exta2-0155"],
    ["Ŗ", "Capital R Cedilla", "exta2-0156"],
    ["ŗ", "Small R Cedilla", "exta2-0157"],
    ["Ř", "Capital R Caron", "exta2-0158"],
    ["ř", "Small R Caron", "exta2-0159"],
    ["Ś", "Capital S Acute", "exta2-015a"],
    ["ś", "Small S Acute", "exta2-015b"],
    ["Ŝ", "Capital S Circumflex", "exta2-015c"],
    ["ŝ", "Small S Circumflex", "exta2-015d"],
    ["Ş", "Capital S Cedilla", "exta2-015e"],
    ["ş", "Small S Cedilla", "exta2-015f"],
    ["Š", "Capital S Caron", "exta2-0160"],
    ["š", "Small S Caron", "exta2-0161"],
    ["Ţ", "Capital T Cedilla", "exta2-0162"],
    ["ţ", "Small T Cedilla", "exta2-0163"],
    ["Ť", "Capital T Caron", "exta2-0164"],
    ["ť", "Small T Caron", "exta2-0165"],
    ["Ŧ", "Capital T Stroke", "exta2-0166"],
    ["ŧ", "Small T Stroke", "exta2-0167"],
    ["Ũ", "Capital U Tilde", "exta2-0168"],
    ["ũ", "Small U Tilde", "exta2-0169"],
    ["Ū", "Capital U Macron", "exta2-016a"],
    ["ū", "Small U Macron", "exta2-016b"],
    ["Ŭ", "Capital U Breve", "exta2-016c"],
    ["ŭ", "Small U Breve", "exta2-016d"],
    ["Ů", "Capital U Ring Above", "exta2-016e"],
    ["ů", "Small U Ring Above", "exta2-016f"],
    ["Ű", "Capital U Double Acute", "exta2-0170"],
    ["ű", "Small U Double Acute", "exta2-0171"],
    ["Ų", "Capital U Ogonek", "exta2-0172"],
    ["ų", "Small U Ogonek", "exta2-0173"],
    ["Ŵ", "Capital W Circumflex", "exta2-0174"],
    ["ŵ", "Small W Circumflex", "exta2-0175"],
    ["Ŷ", "Capital Y Circumflex", "exta2-0176"],
    ["ŷ", "Small Y Circumflex", "exta2-0177"],
    ["Ÿ", "Capital Y Diaeresis", "exta2-0178"],
    ["Ź", "Capital Z Acute", "exta2-0179"],
    ["ź", "Small Z Acute", "exta2-017a"],
    ["Ż", "Capital Z Dot Above", "exta2-017b"],
    ["ż", "Small Z Dot Above", "exta2-017c"],
    ["Ž", "Capital Z Caron", "exta2-017d"],
    ["ž", "Small Z Caron", "exta2-017e"],
    ["ſ", "Small Long S", "exta2-017f"],
  ];

  const latinExtB1Letters = [
    ["ƀ", "Small B Stroke", "extb1-0180"],
    ["Ɓ", "Capital B Hook", "extb1-0181"],
    ["Ƃ", "Capital B Topbar", "extb1-0182"],
    ["ƃ", "Small B Topbar", "extb1-0183"],
    ["Ƅ", "Capital Tone Six", "extb1-0184"],
    ["ƅ", "Small Tone Six", "extb1-0185"],
    ["Ɔ", "Capital Open O", "extb1-0186"],
    ["Ƈ", "Capital C Hook", "extb1-0187"],
    ["ƈ", "Small C Hook", "extb1-0188"],
    ["Ɖ", "Capital African D", "extb1-0189"],
    ["Ɗ", "Capital D Hook", "extb1-018a"],
    ["Ƌ", "Capital D Topbar", "extb1-018b"],
    ["ƌ", "Small D Topbar", "extb1-018c"],
    ["ƍ", "Small Turned Delta", "extb1-018d"],
    ["Ǝ", "Capital Reversed E", "extb1-018e"],
    ["Ə", "Capital Schwa", "extb1-018f"],
    ["Ɛ", "Capital Open E", "extb1-0190"],
    ["Ƒ", "Capital F Hook", "extb1-0191"],
    ["ƒ", "Small F Hook", "extb1-0192"],
    ["Ɠ", "Capital G Hook", "extb1-0193"],
    ["Ɣ", "Capital Gamma", "extb1-0194"],
    ["ƕ", "Small Hv", "extb1-0195"],
    ["Ɩ", "Capital Iota", "extb1-0196"],
    ["Ɨ", "Capital I Stroke", "extb1-0197"],
    ["Ƙ", "Capital K Hook", "extb1-0198"],
    ["ƙ", "Small K Hook", "extb1-0199"],
    ["ƚ", "Small L With Bar", "extb1-019a"],
    ["ƛ", "Small Lambda With Stroke", "extb1-019b"],
    ["Ɯ", "Capital Turned M", "extb1-019c"],
    ["Ɲ", "Capital N Left Hook", "extb1-019d"],
    ["ƞ", "Small N Long Right Leg", "extb1-019e"],
    ["Ɵ", "Capital O Middle Tilde", "extb1-019f"],
    ["Ơ", "Capital O Horn", "extb1-01a0"],
    ["ơ", "Small O Horn", "extb1-01a1"],
    ["Ƣ", "Capital Oi", "extb1-01a2"],
    ["ƣ", "Small Oi", "extb1-01a3"],
    ["Ƥ", "Capital P Hook", "extb1-01a4"],
    ["ƥ", "Small P Hook", "extb1-01a5"],
    ["Ʀ", "Yr", "extb1-01a6"],
    ["Ƨ", "Capital Tone Two", "extb1-01a7"],
    ["ƨ", "Small Tone Two", "extb1-01a8"],
    ["Ʃ", "Capital Esh", "extb1-01a9"],
    ["ƪ", "Small Esh Loop", "extb1-01aa"],
    ["ƫ", "Small T Palatal Hook", "extb1-01ab"],
    ["Ƭ", "Capital T Hook", "extb1-01ac"],
    ["ƭ", "Small T Hook", "extb1-01ad"],
    ["Ʈ", "Capital T Reversed Esh", "extb1-01ae"],
    ["Ư", "Capital U Horn", "extb1-01af"],
    ["ư", "Small U Horn", "extb1-01b0"],
    ["Ʊ", "Capital Upsilon", "extb1-01b1"],
    ["Ʋ", "Capital V Hook", "extb1-01b2"],
    ["Ƴ", "Capital Y Hook", "extb1-01b3"],
    ["ƴ", "Small Y Hook", "extb1-01b4"],
    ["Ƶ", "Capital Z Stroke", "extb1-01b5"],
    ["ƶ", "Small Z Stroke", "extb1-01b6"],
    ["Ʒ", "Capital Ezh", "extb1-01b7"],
    ["Ƹ", "Capital Ezh Reversed", "extb1-01b8"],
    ["ƹ", "Small Ezh Reversed", "extb1-01b9"],
    ["ƺ", "Small Ezh With Tail", "extb1-01ba"],
    ["ƻ", "Small Two With Stroke", "extb1-01bb"],
    ["Ƽ", "Capital Tone Five", "extb1-01bc"],
    ["ƽ", "Small Tone Five", "extb1-01bd"],
    ["ƾ", "Capital Inverted Glottal Stop With Stroke", "extb1-01be"],
    ["ƿ", "Small Wynn", "extb1-01bf"],
  ];

  const latinExtB2Letters = [
    ["ǀ", "Letter Dental Click", "extb2-01c0"],
    ["ǁ", "Letter Lateral Click", "extb2-01c1"],
    ["ǂ", "Letter Alveolar Click", "extb2-01c2"],
    ["ǃ", "Letter Retroflex Click", "extb2-01c3"],
    ["Ǆ", "Capital Dz Caron", "extb2-01c4"],
    ["ǅ", "Capital D Small Z Caron", "extb2-01c5"],
    ["ǆ", "Small Dz Caron", "extb2-01c6"],
    ["Ǉ", "Capital Lj", "extb2-01c7"],
    ["ǈ", "Capital L Small J", "extb2-01c8"],
    ["ǉ", "Small Lj", "extb2-01c9"],
    ["Ǌ", "Capital Nj", "extb2-01ca"],
    ["ǋ", "Capital N Small J", "extb2-01cb"],
    ["ǌ", "Small Nj", "extb2-01cc"],
    ["Ǎ", "Capital A Caron", "extb2-01cd"],
    ["ǎ", "Small A Caron", "extb2-01ce"],
    ["Ǐ", "Capital I Caron", "extb2-01cf"],
    ["ǐ", "Small I Caron", "extb2-01d0"],
    ["Ǒ", "Capital O Caron", "extb2-01d1"],
    ["ǒ", "Small O Caron", "extb2-01d2"],
    ["Ǔ", "Capital U Caron", "extb2-01d3"],
    ["ǔ", "Small U Caron", "extb2-01d4"],
    ["Ǖ", "Capital U Diaeresis Macron", "extb2-01d5"],
    ["ǖ", "Small U Diaeresis Macron", "extb2-01d6"],
    ["Ǘ", "Capital U Diaeresis Acute", "extb2-01d7"],
    ["ǘ", "Small U Diaeresis Acute", "extb2-01d8"],
    ["Ǚ", "Capital U Diaeresis Caron", "extb2-01d9"],
    ["ǚ", "Small U Diaeresis Caron", "extb2-01da"],
    ["Ǜ", "Capital U Diaeresis Grave", "extb2-01db"],
    ["ǜ", "Small U Diaeresis Grave", "extb2-01dc"],
    ["ǝ", "Small Turned E", "extb2-01dd"],
    ["Ǟ", "Capital A Diaeresis Macron", "extb2-01de"],
    ["ǟ", "Small A Diaeresis Macron", "extb2-01df"],
    ["Ǡ", "Capital A Dot Above Macron", "extb2-01e0"],
    ["ǡ", "Small A Dot Above Macron", "extb2-01e1"],
    ["Ǣ", "Capital Ae Macron", "extb2-01e2"],
    ["ǣ", "Small Ae Macron", "extb2-01e3"],
    ["Ǥ", "Capital G Stroke", "extb2-01e4"],
    ["ǥ", "Small G Stroke", "extb2-01e5"],
    ["Ǧ", "Capital G Caron", "extb2-01e6"],
    ["ǧ", "Small G Caron", "extb2-01e7"],
    ["Ǩ", "Capital K Caron", "extb2-01e8"],
    ["ǩ", "Small K Caron", "extb2-01e9"],
    ["Ǫ", "Capital O Ogonek", "extb2-01ea"],
    ["ǫ", "Small O Ogonek", "extb2-01eb"],
    ["Ǭ", "Capital O Ogonek Macron", "extb2-01ec"],
    ["ǭ", "Small O Ogonek Macron", "extb2-01ed"],
    ["Ǯ", "Capital Ezh Caron", "extb2-01ee"],
    ["ǯ", "Small Ezh Caron", "extb2-01ef"],
    ["ǰ", "Small J Caron", "extb2-01f0"],
    ["Ǳ", "Capital Dz", "extb2-01f1"],
    ["ǲ", "Capital D Small Z", "extb2-01f2"],
    ["ǳ", "Small Dz", "extb2-01f3"],
    ["Ǵ", "Capital G Acute", "extb2-01f4"],
    ["ǵ", "Small G Acute", "extb2-01f5"],
    ["Ƕ", "Capital Hwair", "extb2-01f6"],
    ["Ƿ", "Capital Wynn", "extb2-01f7"],
    ["Ǹ", "Capital N Grave", "extb2-01f8"],
    ["ǹ", "Small N Grave", "extb2-01f9"],
    ["Ǻ", "Capital A Ring Above Acute", "extb2-01fa"],
    ["ǻ", "Small A Ring Above Acute", "extb2-01fb"],
    ["Ǽ", "Capital Ae Acute", "extb2-01fc"],
    ["ǽ", "Small Ae Acute", "extb2-01fd"],
    ["Ǿ", "Capital O Stroke Acute", "extb2-01fe"],
    ["ǿ", "Small O Stroke Acute", "extb2-01ff"],
    ["Ȁ", "Capital A Double Grave", "extb2-0200"],
    ["ȁ", "Small A Double Grave", "extb2-0201"],
    ["Ȃ", "Capital A Inverted Breve", "extb2-0202"],
    ["ȃ", "Small A Inverted Breve", "extb2-0203"],
    ["Ȅ", "Capital E Double Grave", "extb2-0204"],
    ["ȅ", "Small E Double Grave", "extb2-0205"],
    ["Ȇ", "Capital E Inverted Breve", "extb2-0206"],
    ["ȇ", "Small E Inverted Breve", "extb2-0207"],
    ["Ȉ", "Capital I Double Grave", "extb2-0208"],
    ["ȉ", "Small I Double Grave", "extb2-0209"],
    ["Ȋ", "Capital I Inverted Breve", "extb2-020a"],
    ["ȋ", "Small I Inverted Breve", "extb2-020b"],
    ["Ȍ", "Capital O Double Grave", "extb2-020c"],
    ["ȍ", "Small O Double Grave", "extb2-020d"],
    ["Ȏ", "Capital O Inverted Breve", "extb2-020e"],
    ["ȏ", "Small O Inverted Breve", "extb2-020f"],
    ["Ȑ", "Capital R Double Grave", "extb2-0210"],
    ["ȑ", "Small R Double Grave", "extb2-0211"],
    ["Ȓ", "Capital R Inverted Breve", "extb2-0212"],
    ["ȓ", "Small R Inverted Breve", "extb2-0213"],
    ["Ȕ", "Capital U Double Grave", "extb2-0214"],
    ["ȕ", "Small U Double Grave", "extb2-0215"],
    ["Ȗ", "Capital U Inverted Breve", "extb2-0216"],
    ["ȗ", "Small U Inverted Breve", "extb2-0217"],
    ["Ș", "Capital S Comma Below", "extb2-0218"],
    ["ș", "Small S Comma Below", "extb2-0219"],
    ["Ț", "Capital T Comma Below", "extb2-021a"],
    ["ț", "Small T Comma Below", "extb2-021b"],
    ["Ȝ", "Capital Yogh", "extb2-021c"],
    ["ȝ", "Small Yogh", "extb2-021d"],
    ["Ȟ", "Capital H Caron", "extb2-021e"],
    ["ȟ", "Small H Caron", "extb2-021f"],
    ["Ƞ", "Capital N Long Right Leg", "extb2-0220"],
    ["ȡ", "Small D Curl", "extb2-0221"],
    ["Ȣ", "Capital Ou", "extb2-0222"],
    ["ȣ", "Small Ou", "extb2-0223"],
    ["Ȥ", "Capital Z Hook", "extb2-0224"],
    ["ȥ", "Small Z Hook", "extb2-0225"],
    ["Ȧ", "Capital A Dot Above", "extb2-0226"],
    ["ȧ", "Small A Dot Above", "extb2-0227"],
    ["Ȩ", "Capital E Cedilla", "extb2-0228"],
    ["ȩ", "Small E Cedilla", "extb2-0229"],
    ["Ȫ", "Capital O Diaeresis Macron", "extb2-022a"],
    ["ȫ", "Small O Diaeresis Macron", "extb2-022b"],
    ["Ȭ", "Capital O Tilde Macron", "extb2-022c"],
    ["ȭ", "Small O Tilde Macron", "extb2-022d"],
    ["Ȯ", "Capital O Dot Above", "extb2-022e"],
    ["ȯ", "Small O Dot Above", "extb2-022f"],
    ["Ȱ", "Capital O Dot Above Macron", "extb2-0230"],
    ["ȱ", "Small O Dot Above Macron", "extb2-0231"],
    ["Ȳ", "Capital Y Macron", "extb2-0232"],
    ["ȳ", "Small Y Macron", "extb2-0233"],
    ["ȴ", "Small L Curl", "extb2-0234"],
    ["ȵ", "Small N Curl", "extb2-0235"],
    ["ȶ", "Small T Curl", "extb2-0236"],
    ["ȷ", "Small Dotless J", "extb2-0237"],
    ["ȸ", "Small Db Digraph", "extb2-0238"],
    ["ȹ", "Small Qp Digraph", "extb2-0239"],
    ["Ⱥ", "Capital A Stroke", "extb2-023a"],
    ["Ȼ", "Capital C Stroke", "extb2-023b"],
    ["ȼ", "Small C Stroke", "extb2-023c"],
    ["Ƚ", "Capital L With Bar", "extb2-023d"],
    ["Ⱦ", "Capital T Diagonal Stroke", "extb2-023e"],
    ["ȿ", "Small S Swash Tail", "extb2-023f"],
    ["ɀ", "Small Z Swash Tail", "extb2-0240"],
    ["Ɂ", "Capital Glottal Stop", "extb2-0241"],
    ["ɂ", "Small Glottal Stop", "extb2-0242"],
    ["Ƀ", "Capital B Stroke", "extb2-0243"],
    ["Ʉ", "Capital U Bar", "extb2-0244"],
    ["Ʌ", "Capital Turned V", "extb2-0245"],
    ["Ɇ", "Capital E Stroke", "extb2-0246"],
    ["ɇ", "Small E Stroke", "extb2-0247"],
    ["Ɉ", "Capital J Stroke", "extb2-0248"],
    ["ɉ", "Small J Stroke", "extb2-0249"],
    ["Ɋ", "Capital Small Q With Hook Tail", "extb2-024a"],
    ["ɋ", "Small Q With Hook Tail", "extb2-024b"],
    ["Ɍ", "Capital R With Stroke", "extb2-024c"],
    ["ɍ", "Small R With Stroke", "extb2-024d"],
    ["Ɏ", "Capital Y With Stroke", "extb2-024e"],
    ["ɏ", "Small Y With Stroke", "extb2-024f"],
  ];

  const latinAdd1Letters = [
    ["Ḁ", "Capital A Ring Below", "add1-1e00"],
    ["ḁ", "Small A Ring Below", "add1-1e01"],
    ["Ḃ", "Capital B Dot Above", "add1-1e02"],
    ["ḃ", "Small B Dot Above", "add1-1e03"],
    ["Ḅ", "Capital B Dot Below", "add1-1e04"],
    ["ḅ", "Small B Dot Below", "add1-1e05"],
    ["Ḇ", "Capital B Line Below", "add1-1e06"],
    ["ḇ", "Small B Line Below", "add1-1e07"],
    ["Ḉ", "Capital C Cedilla + Acute", "add1-1e08"],
    ["ḉ", "Small C Cedilla + Acute", "add1-1e09"],
    ["Ḋ", "Capital D Dot Above", "add1-1e0a"],
    ["ḋ", "Small D Dot Above", "add1-1e0b"],
    ["Ḍ", "Capital D Dot Below", "add1-1e0c"],
    ["ḍ", "Small D Dot Below", "add1-1e0d"],
    ["Ḏ", "Capital D Line Below", "add1-1e0e"],
    ["ḏ", "Small D Line Below", "add1-1e0f"],
    ["Ḑ", "Capital D Cedilla", "add1-1e10"],
    ["ḑ", "Small D Cedilla", "add1-1e11"],
    ["Ḓ", "Capital D Circumflex Below", "add1-1e12"],
    ["ḓ", "Small D Circumflex Below", "add1-1e13"],
    ["Ḕ", "Capital E Macron + Grave", "add1-1e14"],
    ["ḕ", "Small E Macron + Grave", "add1-1e15"],
    ["Ḗ", "Capital E Macron + Acute", "add1-1e16"],
    ["ḗ", "Small E Macron + Acute", "add1-1e17"],
    ["Ḙ", "Capital E Circumflex Below", "add1-1e18"],
    ["ḙ", "Small E Circumflex Below", "add1-1e19"],
    ["Ḛ", "Capital E Tilde Below", "add1-1e1a"],
    ["ḛ", "Small E Tilde Below", "add1-1e1b"],
    ["Ḝ", "Capital E Cedilla + Breve", "add1-1e1c"],
    ["ḝ", "Small E Cedilla + Breve", "add1-1e1d"],
    ["Ḟ", "Capital F Dot Above", "add1-1e1e"],
    ["ḟ", "Small F Dot Above", "add1-1e1f"],
    ["Ḡ", "Capital G Macron", "add1-1e20"],
    ["ḡ", "Small G Macron", "add1-1e21"],
    ["Ḣ", "Capital H Dot Above", "add1-1e22"],
    ["ḣ", "Small H Dot Above", "add1-1e23"],
    ["Ḥ", "Capital H Dot Below", "add1-1e24"],
    ["ḥ", "Small H Dot Below", "add1-1e25"],
    ["Ḧ", "Capital H Diaeresis", "add1-1e26"],
    ["ḧ", "Small H Diaeresis", "add1-1e27"],
    ["Ḩ", "Capital H Cedilla", "add1-1e28"],
    ["ḩ", "Small H Cedilla", "add1-1e29"],
    ["Ḫ", "Capital H Breve Below", "add1-1e2a"],
    ["ḫ", "Small H Breve Below", "add1-1e2b"],
    ["Ḭ", "Capital I Tilde Below", "add1-1e2c"],
    ["ḭ", "Small I Tilde Below", "add1-1e2d"],
    ["Ḯ", "Capital I Diaeresis + Acute", "add1-1e2e"],
    ["ḯ", "Small I Diaeresis + Acute", "add1-1e2f"],
    ["Ḱ", "Capital K Acute", "add1-1e30"],
    ["ḱ", "Small K Acute", "add1-1e31"],
    ["Ḳ", "Capital K Dot Below", "add1-1e32"],
    ["ḳ", "Small K Dot Below", "add1-1e33"],
    ["Ḵ", "Capital K Line Below", "add1-1e34"],
    ["ḵ", "Small K Line Below", "add1-1e35"],
    ["Ḷ", "Capital L Dot Below", "add1-1e36"],
    ["ḷ", "Small L Dot Below", "add1-1e37"],
    ["Ḹ", "Capital L Dot Below Macron", "add1-1e38"],
    ["ḹ", "Small L Dot Below Macron", "add1-1e39"],
    ["Ḻ", "Capital L Line Below", "add1-1e3a"],
    ["ḻ", "Small L Line Below", "add1-1e3b"],
    ["Ḽ", "Capital L Circumflex Below", "add1-1e3c"],
    ["ḽ", "Small L Circumflex Below", "add1-1e3d"],
    ["Ḿ", "Capital M Acute", "add1-1e3e"],
    ["ḿ", "Small M Acute", "add1-1e3f"],
    ["Ṁ", "Capital M Dot Above", "add1-1e40"],
    ["ṁ", "Small M Dot Above", "add1-1e41"],
    ["Ṃ", "Capital M Dot Below", "add1-1e42"],
    ["ṃ", "Small M Dot Below", "add1-1e43"],
    ["Ṅ", "Capital N Dot Above", "add1-1e44"],
    ["ṅ", "Small N Dot Above", "add1-1e45"],
    ["Ṇ", "Capital N Dot Below", "add1-1e46"],
    ["ṇ", "Small N Dot Below", "add1-1e47"],
    ["Ṉ", "Capital N Line Below", "add1-1e48"],
    ["ṉ", "Small N Line Below", "add1-1e49"],
    ["Ṋ", "Capital N Circumflex Below", "add1-1e4a"],
    ["ṋ", "Small N Circumflex Below", "add1-1e4b"],
    ["Ṍ", "Capital O Tilde + Acute", "add1-1e4c"],
    ["ṍ", "Small O Tilde + Acute", "add1-1e4d"],
    ["Ṏ", "Capital O Tilde + Diaeresis", "add1-1e4e"],
    ["ṏ", "Small O Tilde + Diaeresis", "add1-1e4f"],
    ["Ṑ", "Capital O Macron + Grave", "add1-1e50"],
    ["ṑ", "Small O Macron + Grave", "add1-1e51"],
    ["Ṓ", "Capital O Macron + Acute", "add1-1e52"],
    ["ṓ", "Small O Macron + Acute", "add1-1e53"],
    ["Ṕ", "Capital P Acute", "add1-1e54"],
    ["ṕ", "Small P Acute", "add1-1e55"],
    ["Ṗ", "Capital P Dot Above", "add1-1e56"],
    ["ṗ", "Small P Dot Above", "add1-1e57"],
    ["Ṙ", "Capital R Dot Above", "add1-1e58"],
    ["ṙ", "Small R Dot Above", "add1-1e59"],
    ["Ṛ", "Capital R Dot Below", "add1-1e5a"],
    ["ṛ", "Small R Dot Below", "add1-1e5b"],
    ["Ṝ", "Capital R Dot Below Macron", "add1-1e5c"],
    ["ṝ", "Small R Dot Below Macron", "add1-1e5d"],
    ["Ṟ", "Capital R Line Below", "add1-1e5e"],
    ["ṟ", "Small R Line Below", "add1-1e5f"],
    ["Ṡ", "Capital S Dot Above", "add1-1e60"],
    ["ṡ", "Small S Dot Above", "add1-1e61"],
    ["Ṣ", "Capital S Dot Below", "add1-1e62"],
    ["ṣ", "Small S Dot Below", "add1-1e63"],
    ["Ṥ", "Capital S Acute + Dot Above", "add1-1e64"],
    ["ṥ", "Small S Acute + Dot Above", "add1-1e65"],
    ["Ṧ", "Capital S Caron + Dot Above", "add1-1e66"],
    ["ṧ", "Small S Caron + Dot Above", "add1-1e67"],
    ["Ṩ", "Capital S Dot Below + Dot Above", "add1-1e68"],
    ["ṩ", "Small S Dot Below + Dot Above", "add1-1e69"],
    ["Ṫ", "Capital T Dot Above", "add1-1e6a"],
    ["ṫ", "Small T Dot Above", "add1-1e6b"],
    ["Ṭ", "Capital T Dot Below", "add1-1e6c"],
    ["ṭ", "Small T Dot Below", "add1-1e6d"],
    ["Ṯ", "Capital T Line Below", "add1-1e6e"],
    ["ṯ", "Small T Line Below", "add1-1e6f"],
    ["Ṱ", "Capital T Circumflex Below", "add1-1e70"],
    ["ṱ", "Small T Circumflex Below", "add1-1e71"],
    ["Ṳ", "Capital U Diaeresis Below", "add1-1e72"],
    ["ṳ", "Small U Diaeresis Below", "add1-1e73"],
    ["Ṵ", "Capital U Tilde Below", "add1-1e74"],
    ["ṵ", "Small U Tilde Below", "add1-1e75"],
    ["Ṷ", "Capital U Circumflex Below", "add1-1e76"],
    ["ṷ", "Small U Circumflex Below", "add1-1e77"],
    ["Ṹ", "Capital U Tilde + Acute", "add1-1e78"],
    ["ṹ", "Small U Tilde + Acute", "add1-1e79"],
    ["Ṻ", "Capital U Macron + Diaeresis", "add1-1e7a"],
    ["ṻ", "Small U Macron + Diaeresis", "add1-1e7b"],
    ["Ṽ", "Capital V Tilde", "add1-1e7c"],
    ["ṽ", "Small V Tilde", "add1-1e7d"],
    ["Ṿ", "Capital V Dot Below", "add1-1e7e"],
    ["ṿ", "Small V Dot Below", "add1-1e7f"],
  ];

  const latinAdd2Letters = [
    ["Ẁ", "Capital W Grave", "add2-1e80"],
    ["ẁ", "Small W Grave", "add2-1e81"],
    ["Ẃ", "Capital W Acute", "add2-1e82"],
    ["ẃ", "Small W Acute", "add2-1e83"],
    ["Ẅ", "Capital W Diaeresis", "add2-1e84"],
    ["ẅ", "Small W Diaeresis", "add2-1e85"],
    ["Ẇ", "Capital W Dot Above", "add2-1e86"],
    ["ẇ", "Small W Dot Above", "add2-1e87"],
    ["Ẉ", "Capital W Dot Below", "add2-1e88"],
    ["ẉ", "Small W Dot Below", "add2-1e89"],
    ["Ẋ", "Capital X Dot Above", "add2-1e8a"],
    ["ẋ", "Small X Dot Above", "add2-1e8b"],
    ["Ẍ", "Capital X Diaeresis", "add2-1e8c"],
    ["ẍ", "Small X Diaeresis", "add2-1e8d"],
    ["Ẏ", "Capital Y Dot Above", "add2-1e8e"],
    ["ẏ", "Small Y Dot Above", "add2-1e8f"],
    ["Ẑ", "Capital Z Circumflex", "add2-1e90"],
    ["ẑ", "Small Z Circumflex", "add2-1e91"],
    ["Ẓ", "Capital Z Dot Below", "add2-1e92"],
    ["ẓ", "Small Z Dot Below", "add2-1e93"],
    ["Ẕ", "Capital Z Line Below", "add2-1e94"],
    ["ẕ", "Small Z Line Below", "add2-1e95"],
    ["ẖ", "Small H Line Below", "add2-1e96"],
    ["ẗ", "Small T Diaeresis", "add2-1e97"],
    ["ẘ", "Small W Ring Above", "add2-1e98"],
    ["ẙ", "Small Y Ring Above", "add2-1e99"],
    ["ẚ", "Small A Right Half Ring", "add2-1e9a"],
    ["ẛ", "Small Long S Dot Above", "add2-1e9b"],
    ["ẜ", "Small Long S Dot Below", "add2-1e9c"],
    ["ẝ", "Small Long S High Stroke", "add2-1e9d"],
    ["ẞ", "Capital Sharp S", "add2-1e9e"],
    ["ẟ", "Small Delta", "add2-1e9f"],
    ["Ạ", "Capital A Dot Below", "add2-1ea0"],
    ["ạ", "Small A Dot Below", "add2-1ea1"],
    ["Ả", "Capital A Hook Above", "add2-1ea2"],
    ["ả", "Small A Hook Above", "add2-1ea3"],
    ["Ấ", "Capital A Circumflex + Acute", "add2-1ea4"],
    ["ấ", "Small A Circumflex + Acute", "add2-1ea5"],
    ["Ầ", "Capital A Circumflex + Grave", "add2-1ea6"],
    ["ầ", "Small A Circumflex + Grave", "add2-1ea7"],
    ["Ẩ", "Capital A Circumflex + Hook Above", "add2-1ea8"],
    ["ẩ", "Small A Circumflex + Hook Above", "add2-1ea9"],
    ["Ẫ", "Capital A Circumflex + Tilde", "add2-1eaa"],
    ["ẫ", "Small A Circumflex + Tilde", "add2-1eab"],
    ["Ậ", "Capital A Circumflex + Dot Below", "add2-1eac"],
    ["ậ", "Small A Circumflex + Dot Below", "add2-1ead"],
    ["Ắ", "Capital A Breve + Acute", "add2-1eae"],
    ["ắ", "Small A Breve + Acute", "add2-1eaf"],
    ["Ằ", "Capital A Breve + Grave", "add2-1eb0"],
    ["ằ", "Small A Breve + Grave", "add2-1eb1"],
    ["Ẳ", "Capital A Breve + Hook Above", "add2-1eb2"],
    ["ẳ", "Small A Breve + Hook Above", "add2-1eb3"],
    ["Ẵ", "Capital A Breve + Tilde", "add2-1eb4"],
    ["ẵ", "Small A Breve + Tilde", "add2-1eb5"],
    ["Ặ", "Capital A Breve + Dot Below", "add2-1eb6"],
    ["ặ", "Small A Breve + Dot Below", "add2-1eb7"],
    ["Ẹ", "Capital E Dot Below", "add2-1eb8"],
    ["ẹ", "Small E Dot Below", "add2-1eb9"],
    ["Ẻ", "Capital E Hook Above", "add2-1eba"],
    ["ẻ", "Small E Hook Above", "add2-1ebb"],
    ["Ẽ", "Capital E Tilde", "add2-1ebc"],
    ["ẽ", "Small E Tilde", "add2-1ebd"],
    ["Ế", "Capital E Circumflex + Acute", "add2-1ebe"],
    ["ế", "Small E Circumflex + Acute", "add2-1ebf"],
    ["Ề", "Capital E Circumflex + Grave", "add2-1ec0"],
    ["ề", "Small E Circumflex + Grave", "add2-1ec1"],
    ["Ể", "Capital E Circumflex + Hook Above", "add2-1ec2"],
    ["ể", "Small E Circumflex + Hook Above", "add2-1ec3"],
    ["Ễ", "Capital E Circumflex + Tilde", "add2-1ec4"],
    ["ễ", "Small E Circumflex + Tilde", "add2-1ec5"],
    ["Ệ", "Capital E Circumflex + Dot Below", "add2-1ec6"],
    ["ệ", "Small E Circumflex + Dot Below", "add2-1ec7"],
    ["Ỉ", "Capital I Hook Above", "add2-1ec8"],
    ["ỉ", "Small I Hook Above", "add2-1ec9"],
    ["Ị", "Capital I Dot Below", "add2-1eca"],
    ["ị", "Small I Dot Below", "add2-1ecb"],
    ["Ọ", "Capital O Dot Below", "add2-1ecc"],
    ["ọ", "Small O Dot Below", "add2-1ecd"],
    ["Ỏ", "Capital O Hook Above", "add2-1ece"],
    ["ỏ", "Small O Hook Above", "add2-1ecf"],
    ["Ố", "Capital O Circumflex + Acute", "add2-1ed0"],
    ["ố", "Small O Circumflex + Acute", "add2-1ed1"],
    ["Ồ", "Capital O Circumflex + Grave", "add2-1ed2"],
    ["ồ", "Small O Circumflex + Grave", "add2-1ed3"],
    ["Ổ", "Capital O Circumflex + Hook Above", "add2-1ed4"],
    ["ổ", "Small O Circumflex + Hook Above", "add2-1ed5"],
    ["Ỗ", "Capital O Circumflex + Tilde", "add2-1ed6"],
    ["ỗ", "Small O Circumflex + Tilde", "add2-1ed7"],
    ["Ộ", "Capital O Circumflex + Dot Below", "add2-1ed8"],
    ["ộ", "Small O Circumflex + Dot Below", "add2-1ed9"],
    ["Ớ", "Capital O Horn + Acute", "add2-1eda"],
    ["ớ", "Small O Horn + Acute", "add2-1edb"],
    ["Ờ", "Capital O Horn + Grave", "add2-1edc"],
    ["ờ", "Small O Horn + Grave", "add2-1edd"],
    ["Ở", "Capital O Horn + Hook Above", "add2-1ede"],
    ["ở", "Small O Horn + Hook Above", "add2-1edf"],
    ["Ỡ", "Capital O Horn + Tilde", "add2-1ee0"],
    ["ỡ", "Small O Horn + Tilde", "add2-1ee1"],
    ["Ợ", "Capital O Horn + Dot Below", "add2-1ee2"],
    ["ợ", "Small O Horn + Dot Below", "add2-1ee3"],
    ["Ụ", "Capital U Dot Below", "add2-1ee4"],
    ["ụ", "Small U Dot Below", "add2-1ee5"],
    ["Ủ", "Capital U Hook Above", "add2-1ee6"],
    ["ủ", "Small U Hook Above", "add2-1ee7"],
    ["Ứ", "Capital U Horn + Acute", "add2-1ee8"],
    ["ứ", "Small U Horn + Acute", "add2-1ee9"],
    ["Ừ", "Capital U Horn + Grave", "add2-1eea"],
    ["ừ", "Small U Horn + Grave", "add2-1eeb"],
    ["Ử", "Capital U Horn + Hook Above", "add2-1eec"],
    ["ử", "Small U Horn + Hook Above", "add2-1eed"],
    ["Ữ", "Capital U Horn + Tilde", "add2-1eee"],
    ["ữ", "Small U Horn + Tilde", "add2-1eef"],
    ["Ự", "Capital U Horn + Dot Below", "add2-1ef0"],
    ["ự", "Small U Horn + Dot Below", "add2-1ef1"],
    ["Ỳ", "Capital Y Grave", "add2-1ef2"],
    ["ỳ", "Small Y Grave", "add2-1ef3"],
    ["Ỵ", "Capital Y Dot Below", "add2-1ef4"],
    ["ỵ", "Small Y Dot Below", "add2-1ef5"],
    ["Ỷ", "Capital Y Hook Above", "add2-1ef6"],
    ["ỷ", "Small Y Hook Above", "add2-1ef7"],
    ["Ỹ", "Capital Y Tilde", "add2-1ef8"],
    ["ỹ", "Small Y Tilde", "add2-1ef9"],
    ["Ỻ", "Capital Middle Welsh Ll", "add2-1efa"],
    ["ỻ", "Small Middle Welsh Ll", "add2-1efb"],
    ["Ỽ", "Capital Middle Welsh V", "add2-1efc"],
    ["ỽ", "Small Middle Welsh V", "add2-1efd"],
    ["Ỿ", "Capital Y With Loop", "add2-1efe"],
    ["ỿ", "Small Y With Loop", "add2-1eff"],
  ];

  function createKeys(containerId, data) {
    const container = document.getElementById(containerId);

    data.forEach(([letter, name, id]) => {
      const key = document.createElement("div");
      key.className = "alphabet-key";

      if (id) {
        key.id = id;
      }

      const letterSpan = document.createElement("span");
      letterSpan.className = "letter";
      letterSpan.innerText = letter;

      const nameSpan = document.createElement("span");
      nameSpan.className = "name";
      nameSpan.innerText = name;

      key.appendChild(letterSpan);
      key.appendChild(nameSpan);

      key.dataset.unicode = letter;
      key.onclick = function (event) {
        copyToClipboard(letter);
        showTooltip("Copied", event);
      };

      container.appendChild(key);
    });
  }

  async function copyToClipboard(text) {
    try {
      await navigator.clipboard.writeText(text);
    } catch (err) {
      const tempInput = document.createElement("input");
      tempInput.value = text;
      document.body.appendChild(tempInput);
      tempInput.select();
      document.execCommand("copy");
      document.body.removeChild(tempInput);
    }
  }

  function showTooltip(message, event) {
    removeExistingTooltips();

    const tooltip = document.createElement("div");
    tooltip.className = "copy-tooltip";
    tooltip.innerText = message;
    tooltip.style.position = "absolute";
    tooltip.style.backgroundColor = "rgba(0, 0, 0, 0.75)";
    tooltip.style.color = "#fff";
    tooltip.style.padding = "5px 10px";
    tooltip.style.borderRadius = "5px";
    tooltip.style.zIndex = "1000";
    tooltip.style.fontSize = "14px";
    tooltip.style.pointerEvents = "none";

    document.body.appendChild(tooltip);

    const x = event.pageX;
    const y = event.pageY;
    tooltip.style.left = `${x - tooltip.offsetWidth / 2}px`;
    tooltip.style.top = `${y - tooltip.offsetHeight - 10}px`;

    setTimeout(() => {
      if (tooltip.parentElement) {
        tooltip.parentElement.removeChild(tooltip);
      }
    }, 1500);
  }

  function removeExistingTooltips() {
    const tooltips = document.querySelectorAll(".copy-tooltip");
    tooltips.forEach((tooltip) => {
      if (tooltip.parentElement) {
        tooltip.parentElement.removeChild(tooltip);
      }
    });
  }

  createKeys("latin1-letters-container", latin1Letters);
  createKeys("latin-ext-a1-container", latinExtA1Letters);
  createKeys("latin-ext-a2-container", latinExtA2Letters);
  createKeys("latin-ext-b1-container", latinExtB1Letters);
  createKeys("latin-ext-b2-container", latinExtB2Letters);
  createKeys("latin-add1-container", latinAdd1Letters);
  createKeys("latin-add2-container", latinAdd2Letters);
});
